version: '3.8'
services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_USER=fastapi_user
      - DB_PASSWORD=fastapi_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fastapi_db
    volumes:
      - .:/app
    command: ["sh", "-c", "alembic -c alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_pass
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
