"""Users Table

Revision ID: 52b16de2c4bc
Revises: 
Create Date: 2025-10-06 11:47:09.464837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '52b16de2c4bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_nodes_id'), table_name='story_nodes')
    op.drop_index(op.f('ix_story_nodes_story_id'), table_name='story_nodes')
    op.drop_table('story_nodes')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_session_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_title'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_register_id'), table_name='register')
    op.drop_index(op.f('ix_register_story_id'), table_name='register')
    op.drop_table('register')
    op.drop_index(op.f('ix_story_jobs_id'), table_name='story_jobs')
    op.drop_index(op.f('ix_story_jobs_job_id'), table_name='story_jobs')
    op.drop_index(op.f('ix_story_jobs_session_id'), table_name='story_jobs')
    op.drop_table('story_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('theme', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('story_id', sa.INTEGER(), nullable=True),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_jobs_session_id'), 'story_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_story_jobs_job_id'), 'story_jobs', ['job_id'], unique=1)
    op.create_index(op.f('ix_story_jobs_id'), 'story_jobs', ['id'], unique=False)
    op.create_table('register',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('is_root', sa.BOOLEAN(), nullable=True),
    sa.Column('is_ending', sa.BOOLEAN(), nullable=True),
    sa.Column('is_winning_ending', sa.BOOLEAN(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_story_id'), 'register', ['story_id'], unique=False)
    op.create_index(op.f('ix_register_id'), 'register', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_title'), 'stories', ['title'], unique=False)
    op.create_index(op.f('ix_stories_session_id'), 'stories', ['session_id'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('story_nodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('is_root', sa.BOOLEAN(), nullable=True),
    sa.Column('is_ending', sa.BOOLEAN(), nullable=True),
    sa.Column('is_winning_ending', sa.BOOLEAN(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_nodes_story_id'), 'story_nodes', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_nodes_id'), 'story_nodes', ['id'], unique=False)
    # ### end Alembic commands ###
