"""add profile_pic to users 2

Revision ID: 8a3fbc00ed54
Revises: eb6ccfa8e76f
Create Date: 2025-10-08 13:10:54.935850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3fbc00ed54'
down_revision: Union[str, Sequence[str], None] = 'eb6ccfa8e76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
